package wrm.progetto_wrm.UTILITIES.Exceptions;

public class TaskAlreadyInUseException extends RuntimeException{
    public TaskAlreadyInUseException () {}
}
